config/routes.rb
App::Application.routes.draw do

  resources :profiles

  resources :fish

  post "profiles/:id" => "fish#follow_post"

  get "/recent" => "fish#recent"

  get "/user/:name" => "fish#user_pics", as: "user_pics"

  root "main#index"

  get "/login" => "main#login_get"

  get "/sign_up" => "main#sign_up_get"

  post "/sign_up" => "main#sign_up_post"

  get "/fish_id" => "main#fish_id_get", as: "fish_id"

  get "/about" => "main#about"

  get "/logout" => "main#logout"

  get "/logged_out" => "main#logged_out_get"

  post "/login" => "main#login_post"

  get "/fish_profile/:fish" => "main#fish_profile"

  get "/verify_email/:user_id/:token" => "main#verify_email",
    as: "verify_email"

  post "/resend_verification_email" => "users#resend_verification_email",
    as: "resend_verification_email"


end

app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  
  def index
    @profiles = Profile.all
  end

  def new
    @profile = Profile.new
  end
  
  def create
    @profile = Profile.new(profile_params)
     @profile.user_id = current_user.id

    if @profile.save
      redirect_to @profile, notice: 'Profile was successfully created.' 
    else
      render action: 'new' 
    end
 
  end

  
  def update
    if @profile.update(profile_params)
      redirect_to @profile, notice: 'Profile was successfully updated.'   
    else
      render action: 'edit' 
    end
  end


  def destroy
    @profile.destroy
  
    redirect_to profiles_url 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:avatar, :avatar_file_name, :location, :birth_year, :favorite_target, :best_catch, :short_bio)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @profile, html: { multipart: true } do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Profile Pic" %><br>
    <%= f.file_field :avatar %>
  </div>

  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :birth_year %><br>
    <%= f.text_field :birth_year, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :favorite_target %><br>
    <%= f.text_field :favorite_target, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :best_catch %><br>
    <%= f.text_field :best_catch, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :short_bio %><br>
    <%= f.text_field :short_bio, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to @profile do %> 
<span class="glyphicon glyphicon-step-backward">Back</span>|
<%end%>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Location</th>
      <th>Birth year</th>
      <th>Favorite target</th>
      <th>Best catch</th>
      <th>Short bio</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user.username if profile.user %></td>
        <td><%= image_tag @profile.avatar.url %></td>
        <td><%= profile.location %></td>
        <td><%= profile.birth_year %></td>
        <td><%= profile.favorite_target %></td>
        <td><%= profile.best_catch %></td>
        <td><%= profile.short_bio %></td>
         <td><%= link_to 'Show', profile %></td>
       <% if profile.user == current_user %>
        <td><%= link_to edit_profile_path(profile) do %></td>
        <span class="glyphicon glyphicon-edit">Edit</span>
        <%end%>
        <td><%= link_to profile, method: :delete, data: { confirm: 'Are you sure?' } do %></td>
        <span class="glyphicon glyphicon-remove">Delete</span>
        <%end%>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user != nil %>
<%= link_to 'New Profile', new_profile_path %>
<%end%>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<% if current_user.profile == nil %>
  <%= link_to 'New Profile', new_profile_path %>
<%end%>

  <p id="notice"><%= notice %></p>

<h1><%= @profile.user.username %> </h1>
  <%= image_tag @profile.avatar.url(:medium) %>
<p>
  <strong>Location:</strong>
  <%= @profile.location %>
</p>

<p>
  <strong>Birth year:</strong>
  <%= @profile.birth_year %>
</p>

<p>
  <strong>Favorite target:</strong>
  <%= @profile.favorite_target %>
</p>

<p>
  <strong>Best catch:</strong>
  <%= @profile.best_catch %>
</p>

<p>
  <strong>Short bio:</strong>
  <%= @profile.short_bio %>
</p>

<% if current_user.id == @profile.user_id %>

  <%= link_to edit_profile_path(@profile) do %> 
  <span class="glyphicon glyphicon-edit">Edit-Profile</span>|
  <%end%>
  
  <%= link_to new_fish_path do %> 
  <span class="glyphicon glyphicon-plus">Add-Fish</span>|
  <%end%>

  <%= link_to fish_index_path(@profile) do %>
  <span class="glyphicon glyphicon-th"><%=current_user.username%>'s-Fish</span>|
  <%end%>
  <h3>Who I follow</h3>

<ul>
  <% current_user.followings_from_me.each do |following| %>
    <li>
      <a href="/profiles/<%=following.to_user.profile.id%>"><%=image_tag following.to_user.profile.avatar.url(:thumb) %></a>
    </li>
    <br>
 <% end %>
</ul>

<%end%>
  <% if current_user.id != @profile.user_id %>
  <%= link_to user_pics_path(@profile.user.username) do %>
  <span class="glyphicon glyphicon-th"><%=@profile.user.username%>'s-Fish</span>
  <%end%>

  <br>
  <% if Following.find_by(from_user_id: current_user.id, to_user_id: @profile.user_id) == nil %>
  <%= form_tag "/profiles/#{@profile.id}" do%>
  <%= submit_tag "Follow" %>
  <%end%>
  <%end%>
  <% if Following.find_by(from_user_id: current_user.id, to_user_id: @profile.user_id) != nil %>
  <%= form_tag "/profiles/#{@profile.id}" do%>
  <%= submit_tag "Unfollow" %>
  <%end%>
  <%end%>

  <%end%>