config/routes.rb
App::Application.routes.draw do

  resources :profiles

  resources :fish

  post "profiles/:id" => "fish#follow_post"

  get "/recent" => "fish#recent"

  get "/user/:name" => "fish#user_pics", as: "user_pics"

  root "main#index"

  get "/login" => "main#login_get"

  get "/sign_up" => "main#sign_up_get"

  post "/sign_up" => "main#sign_up_post"

  get "/fish_id" => "main#fish_id_get", as: "fish_id"

  get "/about" => "main#about"

  get "/logout" => "main#logout"

  get "/logged_out" => "main#logged_out_get"

  post "/login" => "main#login_post"

  get "/fish_profile/:fish" => "main#fish_profile"

  get "/verify_email/:user_id/:token" => "main#verify_email",
    as: "verify_email"

  post "/resend_verification_email" => "users#resend_verification_email",
    as: "resend_verification_email"


end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Fish Log</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
    
      <ul class="nav navbar-nav navbar-right">
         <li><a href="/about">About</a></li>
       
        <li><%= link_to 'Fish Id', fish_id_path %></li>

        <li><a href="/recent">Recent Pics</a></li>
        
        <% if current_user != nil %>
        <li><%= link_to 'Add Fish', new_fish_path %></a></li>
        
        <li><%= link_to "#{current_user.username}", current_user.profile %></a></li>
        
        <li><a href="/logout">Logout <%= current_user.username %></a></li>  
      </ul>
    </div>
    <%end%>
  </div>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>



  <title>App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/

minified/jquery-ui.min.css" type="text/css" media="all">
</head>
<body>

  <%= render 'layouts/header' %>
  <div class="container">
   <%= yield %>
 </div>

 <% if flash[:success] != nil %>
<div class="alert alert-danger">
  <%= flash[:success] %>
</div>

<% if flash[:remind_to_verify_email] %>
  <div class="alert alert-info">
    Please click the link in the email you were sent to verify your email address.
    <%= form_tag resend_verification_email_path do %>
      <%= hidden_field_tag :afterwards_go_to, request.path_info %>
      <%= submit_tag "Resend email" %>
    <% end %>
  </div>
<% end %>
<%end%>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js" 

type="text/javascript"></script>

<script>

 $(function() {

 $(".datepicker").datepicker({ dateFormat: "yy-mm-dd" });

 });

</script>

</body>

<% if flash[:error] != nil %>
<div class="alert alert-danger">
  <%= flash[:error] %>
</div>
<% end %>
<% if flash[:error2] != nil %>
<div class="alert alert-danger">
  <%= flash[:error2] %>
</div>
<%end%>
</html>