config/routes.rb
App::Application.routes.draw do

  resources :profiles

  resources :fish

  post "profiles/:id" => "fish#follow_post"

  get "/recent" => "fish#recent"

  get "/user/:name" => "fish#user_pics", as: "user_pics"

  root "main#index"

  get "/login" => "main#login_get"

  get "/sign_up" => "main#sign_up_get"

  post "/sign_up" => "main#sign_up_post"

  get "/fish_id" => "main#fish_id_get", as: "fish_id"

  get "/about" => "main#about"

  get "/logout" => "main#logout"

  get "/logged_out" => "main#logged_out_get"

  post "/login" => "main#login_post"

  get "/fish_profile/:fish" => "main#fish_profile"

  get "/verify_email/:user_id/:token" => "main#verify_email",
    as: "verify_email"

  post "/resend_verification_email" => "users#resend_verification_email",
    as: "resend_verification_email"


end

app/models/fish.rb
class Fish < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>", :large => "500x500" }
end

app/models/fish_type.rb
class FishType < ActiveRecord::Base
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
  before_action :set_fish, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :ensure_signed_in, only: :index

  def index
    @fish = Fish.order("created_at DESC").page(params[:page]).per_page(8)
  end

  def recent
    @fish = Fish.order("created_at DESC").page(params[:page]).per_page(8)
  end

  

  def follow_post
    profile = Profile.find_by(id: params[:id])
    id = params[:id]
    if params[:commit] == "Follow"
      Following.create! from_user_id: current_user.id, to_user_id: profile.user.id
      redirect_to profile_path
    elsif params[:commit] == "Unfollow"
      following = Following.find_by(from_user_id: current_user.id, to_user_id: profile.user.id)
      following.destroy
      redirect_to profile_path
    end
  end


  def user_pics
    name = params[:name]
    @user = User.find_by(username: name)
  end

  def new
    @fish = Fish.new
  end

  def create
    @fish = current_user.fish.build(fish_params)

    if @fish.save
      redirect_to @fish, notice: 'Fish was successfully created.' 
    else
      render action: 'new' 
    end
  end

  def update
    if @fish.update(fish_params)
      redirect_to @fish, notice: 'Fish was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @fish.destroy
    redirect_to fish_index_url 
  end

  private

  def set_fish
    @fish = Fish.find(params[:id])
  end

  def correct_user
    if @fish.user != current_user
      flash[:error] = "Not authorized to edit this fish"
      redirect_to "/fish"
    end
  end

  def fish_params
    params.require(:fish).permit(:image, :date, :location, :species, :lenth, :weight, :bait, :depth, :temperature, :other_notes)
  end
end

app/helpers/fish_helper.rb
module FishHelper
end

app/views/fish/_form.html.erb
<%= form_for @fish, html: { multipart: true } do |f| %>
  <% if @fish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fish.errors.count, "error") %> prohibited this fish from being saved:</h2>

      <ul>
      <% @fish.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

  <div class="field">
    <%= f.label :date, "Date Caught" %><br>
    <%= f.text_field :date, class: "datepicker", placeholder: "YYYY-MM-DD"%>
  </div>
  <br>

  <div class="form-group">
    <%= f.label :location %><br>
    <%= f.text_field :location, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :species %><br>
    <%= f.text_field :species, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :length %><br>
    <%= f.text_field :lenth, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :weight %><br>
    <%= f.text_field :weight, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bait %><br>
    <%= f.text_field :bait, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :depth %><br>
    <%= f.text_field :depth, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :other_notes %><br>
    <%= f.text_field :other_notes, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/fish/edit.html.erb
<h1>Edit fish</h1>

<%= render 'form' %>

<%= link_to 'Show', @fish %> |
<%= link_to 'Back', fish_index_path %>

app/views/fish/index.html.erb
<h1><%=current_user.username%>'s Fish</h1>


  <div id="fish" class="transitions-enabled">
    
    <% current_user.fish.page(params[:page]).per_page(8).each do |fish| %>
      <div class="box panel panel-default">
      <%= link_to image_tag(fish.image.url(:medium)), fish %>
      <div class="panel-body">
        

        <%= fish.species %>
      <div class="actions">
        <%= link_to fish do %>
        <span class="glyphicon glyphicon-info-sign">Details</span>
        <%end%>|
        <% if fish.user == current_user %>
        <%= link_to edit_fish_path(fish) do %>
        <span class="glyphicon glyphicon-edit">Edit</span>
        <%end%>|
        <%= link_to fish, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-remove">Delete</span>
        <%end%>
      <%end%>
        </div>
        </div>
        </div>
    <% end %>
  </div>

  <%= will_paginate @fish %>

app/views/fish/new.html.erb
<h1>New fish</h1>

<%= render 'form' %>

<%= link_to fish_index_path do %>
<span class="glyphicon glyphicon-th"><%=current_user.username%>'s-Fish</span>
<%end%>

app/views/fish/recent.html.erb
  
<h1>Recent Fish</h1>

<div id="fish" class="transitions-enabled">
  <%newest_fish = Fish.order("created_at DESC").page(params[:page]).per_page(8)%>
  <% newest_fish.each do |fish| %>
  <div class="box panel panel-default">
    <%= link_to image_tag(fish.image.url(:medium)), fish %>
    <div class="panel-body">


      <%= fish.species %>
      <div class="actions">
        <%= link_to fish do %>
        <span class="glyphicon glyphicon-info-sign">Details</span>
        <%end%>|
        <% if fish.user == current_user %>
        <%= link_to edit_fish_path(fish) do %>
        <span class="glyphicon glyphicon-edit">Edit</span>
        <%end%>|
        <%= link_to fish, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-remove">Delete</span>
        <%end%>|
        <%end%>
         <% if fish.user != current_user && current_user != nil%>
        <%= link_to fish.user.profile do %>
        <span class="glyphicon glyphicon-user">Profile</span>
        <%end%>|
        <%end%>
      </div>
    </div>
  </div>
  <% end %>
</div>
<%= will_paginate @fish %>

app/views/fish/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel heading center">
    <%= image_tag @fish.image.url(:large) %>
      </div>
      <div class="panel body center">
    <p>
      <b>Date:</b>
      <%= @fish.date%>
    </p>
    <p>
      <b>Location:</b>
      <%= @fish.location %>
    </p>

    <p>
      <strong>Species:</strong>
      <%= @fish.species %>
    </p>

    <p>
      <strong>Lenth:</strong>
      <%= @fish.lenth %>
    </p>

    <p>
      <strong>Weight:</strong>
      <%= @fish.weight %>
    </p>

    <p>
      <strong>Bait:</strong>
      <%= @fish.bait %>
    </p>

    <p>
      <strong>Depth:</strong>
      <%= @fish.depth %>
    </p>

    <p>
      <strong>Temperature:</strong>
      <%= @fish.temperature %>
    </p>

    <p>
      <strong>Other notes:</strong>
      <%= @fish.other_notes %>
    </p>
</div>
</div>

<% if current_user != nil && current_user.id == @fish.user_id %>
  <%= link_to edit_fish_path do %>
        <span class="glyphicon glyphicon-edit">Edit</span>
        <%end%>|
          <%= link_to fish_index_path do %>
        <span class="glyphicon glyphicon-th"><%=current_user.username%>'s-Fish</span>
        <%end%>|
     
          <%= link_to fish_index_path do %>
          <span class="glyphicon glyphicon-step-backward">Back</span>
      <%end%>
      <%end%>
       <%= link_to recent_path do %>
          <span class="glyphicon glyphicon-step-backward">Recent</span>
<%end%>

app/views/fish/user_pics.html.erb
<% if @user != nil %>
<h1><%=@user.username%>'s Fish</h1>


  <div id="fish" class="transitions-enabled">
    
    <% @user.fish.each do |fish| %>
      <div class="box panel panel-default">
      <%= link_to image_tag(fish.image.url(:medium)), fish %>
      <div class="panel-body">
        

        <%= fish.species %>
      <div class="actions">
        <%= link_to fish do %>
        <span class="glyphicon glyphicon-info-sign">Details</span>
        <%end%>|
        <% if fish.user == current_user %>
        <%= link_to edit_fish_path(fish) do %>
        <span class="glyphicon glyphicon-edit">Edit</span>
        <%end%>|
        <%= link_to fish, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <span class="glyphicon glyphicon-remove">Delete</span>
        <%end%>
      <%end%>
        </div>
        </div>
        </div>
    <% end %>
  </div>
<%end%>